controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

weather_forecast:
    path: /weather/forecast/{lat}/{lon}
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\TetController::getWeatherForecast
    methods:    GET|HEAD